push pr

diff --git a/.github/workflows/update_post.yml b/.github/workflows/update_post.yml
--- a/.github/workflows/update_post.yml
+++ b/.github/workflows/update_post.yml
@@ -47,26 +47,29 @@ jobs:
           GH_TOKEN: ${{ github.token }}
         run: |
           gh pr checkout ${{ github.event.inputs.PR_NUM }}
-          # readonly OLD_POST="${{ github.event.inputs.post_name }}"
-          # readonly NEW_DATE="$(date '+%Y-%m-%d')"
+
+          readonly OLD_POST="${{ github.event.inputs.post_name }}"
+          readonly NEW_DATE="$(date '+%Y-%m-%d')"
           
-          # if [ ! -f "_posts/${OLD_POST}" ]; then
-          #   echo "Blog post ${OLD_POST} not found"
-          #   exit 1
-          # fi
+          if [ ! -f "_posts/${OLD_POST}" ]; then
+            echo "Blog post ${OLD_POST} not found"
+            exit 1
+          fi
 
-          # readonly OLD_DATE=$(echo ${OLD_POST} | sed -E "s/([0-9]{4}\-[0-9]{2}\-[0-9]{2}).*/\1/")
+          readonly OLD_DATE=$(echo ${OLD_POST} | sed -E "s/([0-9]{4}\-[0-9]{2}\-[0-9]{2}).*/\1/")
 
-          # echo "Replacing ${OLD_DATE} in the blog post"
-          # sed -E -i "s/date:( *)${OLD_DATE}/date:\1${NEW_DATE}/"  "_posts/${OLD_POST}"
+          echo "Replacing ${OLD_DATE} in the blog post"
+          sed -E -i "s/date:( *)${OLD_DATE}/date:\1${NEW_DATE}/"  "_posts/${OLD_POST}"
 
-          # readonly NEW_POST="${NEW_DATE}"`echo "${OLD_POST}" | sed -E "s/[0-9]{4}\-[0-9]{2}\-[0-9]{2}//"`
-          # echo "Renaming the ${OLD_POST} to ${NEW_POST}"
+          readonly NEW_POST="${NEW_DATE}"`echo "${OLD_POST}" | sed -E "s/[0-9]{4}\-[0-9]{2}\-[0-9]{2}//"`
+          echo "Renaming the ${OLD_POST} to ${NEW_POST}"
 
-          # git mv _posts/${OLD_POST} _posts/${NEW_POST}
-          # git config --global user.name "Wildfly.org CI"
-          # git config --global user.email "wildfly-dev@lists.jboss.org"
+          git mv _posts/${OLD_POST} _posts/${NEW_POST}
+          git config --global user.name "Wildfly.org CI"
+          git config --global user.email "wildfly-dev@lists.jboss.org"
           
-          # echo "Committing changes and updating the PR" 
-          # git commit -am "Update ${OLD_POST} blog date"
+          echo "Committing changes and updating the PR" 
+          git commit -am "Update ${OLD_POST} blog date"
+
+          gh pr create --title "The bug is fixed" --body "Everything works again" --repository spyrkob/wildfly.org
           # git push
